config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show] do
    resources :items, only: [ :create, :destroy]
  end

  resources :items, only: [:new]
  get 'about' => 'welcome#about'

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :confirmable,
  :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :items, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  #, except: [:index, :show, :about]

  #def after_sign_in_path_for(resource_or_scope)
    #user_path(current_user)
  #end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to current_user
    else
      flash.now[:alert] = "Error creating item. Please try again later."
      render :new
    end
  end

  def destroy
     @item = Item.find(params[:id]).destroy
     respond_to do |format|
       format.html { redirect_to root_path, notice: 'Item deleted' }
       format.js
     end
     redirect_to current_user
  end


  private
  def item_params
    params.require(:item).permit(:name)
end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @items = current_user.items
    @item = Item.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for  [current_user, @item]  do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', placeholder: "Enter item name",  autofocus: true %>
</div>
<div class="form-group">
  <%= f.submit "Save", class: 'btn btn-success' %>
</div>
<% end %>

app/views/items/_item.html.erb
<div class="media todo-item">
  <div class="media-body">
    <div class="mx-auto">
      <%= link_to '', [item.user, item], method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
      <span class='item-name pl-sm'>
        <%= item.name %>
      </span>
      <p class='text-muted pt-sm'>
        Created <%= time_ago_in_words(item.created_at) %> ago
      </p>
    </div>
  </div>
</div>

app/views/items/destroy.js.erb
$('.delete').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
});

app/views/items/new.html.erb
<h1>New Item</h1>

<div class="row">
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg fixed-top">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-4" >
      <li class="nav-item"><%= active_link_to  "Blocitoff", root_path, :class=> "navbar-brand" %></li>
      <li class="nav-item"><%= active_link_to "About",  about_path, :class => "navbar-brand"%></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="nav-item"><%= active_link_to "Edit profile", edit_user_registration_path, :class => 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link'%></li>
        <% else %>
        <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link'  %></li>
        <li class="nav-item"><%= link_to "Sign In", new_user_session_path, :class => 'nav-link'  %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <header class="header">
<div class="overlay"></div>
<div class="container">
  <%= yield %>
  </header>

  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
  <% end %>
  <div class="container">

  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1 class="media-heading" > User: <%= current_user.email %></h1>

    <h3 class="card-subtitle mb-2 text-muted">To-Do List:</h3>
    <p class="card-text">
      <% @items.each do |item| %>
      <%= render item %>
      <% end %>
    </p>
    <div class="col-md-4">
      <%= link_to "New Item", new_item_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Bloccitoff</h1>
<p>Created by: Mariya Baltabaeva</p>

<button class="social-btn"><%= link_to "Let's connect!", "https://www.linkedin.com/in/mariya-baltabaeva/" %>
</button>

app/views/welcome/index.html.erb
<div class="description ">

    <h1>Blocitoff is self-destructing to-do lists!</h1>
    <p>
       <%= link_to "Sign In", new_user_session_path, class: 'btn btn-info'%> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info' %> today!
    </p>
  </div><!-- /.container -->